### ISSUE TITLE
How to add a top level "about" page?

### ISSUE THREAD

**Issue by bilal-fazlani** [Tazeg/hugo-blog-jeffprod#10]

**Comment by Tazeg** [comment]
In the file `layouts/partials/footer.html`, we already have a link to the about page : 

`<a class="mysocial" href="{{ "about" | absURL }}">About</a>`

And in `layouts/partials/header.html` we have the top level home link : 

`<a class="navbar-item" href="{{ .Site.BaseURL | absURL }}">Home</a>`

So under this line add this one : 

`<a class="navbar-item" href="{ "about" | absURL }}">About</a>`

In console, type : 
`hugo new about.md`

And add this as content in the `content/about.md` file : 

```markdown
---
title: "About"
date: 2019-03-22T09:53:29+01:00
tags: []
author: John SMITH
---

about
```
Then you should see the "About" link just after the "Home" link, at the top left of pages.

**Comment by bilal-fazlani** [comment]
Thanks!
