### ISSUE TITLE
Categories, and multiple authors

### ISSUE THREAD

**Issue by lukasz-matysiewicz** [Tazeg/hugo-blog-jeffprod#11]
Is there a change to add categories and multiple authors to this theme?
I tried those steps: https://www.thepolyglotdeveloper.com/2018/04/manage-multiple-authors-static-blog-created-hugo/

I added those in blog post: 
```
author: name
categories: [ "name, name" ]
```
and in config.toml
```
[taxonomies]
    category = "categories"
    author = "authors"
```
plus author file in data/author
But not results, any ideas?

**Comment by Tazeg** [comment]
So, you have created `data/authors/*.json` files.
About getting authors information in the blog posts, copy `layouts/_default/single.html` to `layouts/posts/single.html` and change it like this : 
```html
{{ define "main" }}

<div class="columns">
    <div class="column is-9">
        <div class="tile is-child box">
            <div class="content">
                {{ .Content }}
            {{ if isset .Params "author" }}
                {{ $author := index .Site.Data.authors .Params.author }}
                {{ $author.name }}
                {{ $author.social.github }}
            {{ else }}
                Unknown
            {{ end }}
            </div>
        </div>
    </div>
    <div class="column is-3">
        {{ partial "widget-tags.html" . }}<br>
        {{ partial "widget-recent.html" . }}<br>
        {{ partial "widget-related.html" . }}<br>
        {{ partial "widget-archives.html" . }}
    </div>
</div>

{{ end }}
```

Then in the front matter of a blog post : `content/post/mypost.md`, add `author: "toto"` and the data of `toto.json` will be displayed.
