### ISSUE TITLE
UTF-8 encoding Metatag not working for firefox & safari

### ISSUE THREAD

**Issue by tillepille** [Tazeg/hugo-blog-jeffprod#13]
I used some German letters in my texts like ```ü,ä,ö``` wich traditionally need extra html code. With UTF-8 this is gone.
Unfortunately I had some issues with this in this theme: 

- MacOS
  - Firefox 66.0.5
  - Safari 12.1.1
Chromium/Chrome shows everything correct.

Indicated by [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta) the ```/``` isn't necessary on the end of [this](https://github.com/Tazeg/hugo-blog-jeffprod/blob/master/layouts/partials/header.html#L4) Line. 

```<meta charset="utf-8">```

I removed the slash and it works for me, maybe you want to add it to the theme?

**Comment by Tazeg** [comment]
Thanks. Fixed in 1908f284bddad741f0e9bafd169aa1c77b81302a

**Comment by tillepille** [comment]
That was fast, thanks! 🙌🏻
