### ISSUE TITLE
Page.RSSLink is deprecated

### ISSUE THREAD

**Issue by Karreg** [Tazeg/hugo-blog-jeffprod#15]
Hello,

I have just discovered your theme, that is the best I found with tags widget :)

However, when I build my site, I have this warning that could become an issue in the future:

```
WARN 2020/05/26 11:46:07 Page.RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}
```

**Comment by Tazeg** [comment]
Thanks, i'll fix it as soon as possible.

**Comment by Tazeg** [comment]
fixed https://github.com/Tazeg/hugo-blog-jeffprod/commit/bbe726e57038b97df811731330fe2c35f5043964
