### ISSUE TITLE
I want to list recent posts alongside archieve sidebar

### ISSUE THREAD

**Issue by riturajb** [Tazeg/hugo-blog-jeffprod#2]
Would appreciate if you could guide me on how-to add that. As of now , on homepage I see only tags - and archives page is empty - recently added docs are not showing over there.
I did add code to show list of posts to archive - but then when I open a post - the content is open in main page as well as in the sidebar - whereas sidebar should only list the pages.

**Comment by Tazeg** [comment]
I added a widget to list the last 5 posts : 0a88ef0a1f8453288f2497074308de1c9b56d524
