### ISSUE TITLE
Add colourful code highlight 

### ISSUE THREAD

**Issue by korney4eg** [Tazeg/hugo-blog-jeffprod#6]
Hello, would be nice to add colourful code highlight.
Example: https://fr.jeffprod.com/blog/2018/limiter-le-nombre-de-requetes-vers-une-api/

**Comment by Tazeg** [comment]
This is done by Hugo.
You can highlight code with markdown. For exemple in post/yourpost.md : 

    ```php
    <?php
    phpinfo();
    ```
Doc : 
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code
https://gohugo.io/content-management/syntax-highlighting/
