### ISSUE TITLE
Add search bar to the top menu

### ISSUE THREAD

**Issue by korney4eg** [Tazeg/hugo-blog-jeffprod#7]
would be nice to implement search bar, as it described https://en.jeffprod.com/blog/2018/build-your-own-hugo-website-search-engine/

**Comment by Tazeg** [comment]
Thanks but I'd like to keep this sample hugo template simple, and let people free to use any search they want, as described at https://gohugo.io/tools/search

**Comment by korney4eg** [comment]
BTW, thank you for great theme.

Why I'm creating all this issues - I really like the theme you make, and also I would like to make more universal theme, that can be used without too much  tweaking.
As an example from Hugo: https://github.com/appernetic/hugo-bootstrap-premium
As I moved from Jekyll I used theme: https://github.com/sylhare/Type-on-Strap

The key feature there is following: by adding configuration like twitter account, Google analytics, Disquss to config.toml[yaml] you can enable disable some icons.

If you ok to add some features (some of them you already have in your site) I can send PRs or create issues. If you would like to keep theme as simple as possible it is still ok, as it is open-source and I would just fork your theme.

Anyway thank you for making great theme.

**Comment by Tazeg** [comment]
I also moved from Jekyll ;)
Yes, please fork to add features, and i wish you have contribs.
I won't have time to manage contribs here, so i'd like this repo to be really basic. 
It is for sample purpose to help to start with Hugo. It's not aim to be a clone of my website ;)
